class TtcTracker {
  final String id;
  final String userId;
  final DateTime? lastMenstrualPeriod;
  final int cycleLength;
  final DateTime? estimatedOvulation;
  final DateTime? fertileWindowStart;
  final DateTime? fertileWindowEnd;
  final bool isActivelyTtc;
  final DateTime createdAt;
  final DateTime updatedAt;

  TtcTracker({
    required this.id,
    required this.userId,
    this.lastMenstrualPeriod,
    this.cycleLength = 28,
    this.estimatedOvulation,
    this.fertileWindowStart,
    this.fertileWindowEnd,
    this.isActivelyTtc = true,
    required this.createdAt,
    required this.updatedAt,
  });

  factory TtcTracker.fromMap(Map<String, dynamic> map) {
    return TtcTracker(
      id: map['id'] as String,
      userId: map['user_id'] as String,
      lastMenstrualPeriod: map['last_menstrual_period'] != null
          ? DateTime.parse(map['last_menstrual_period'] as String)
          : null,
      cycleLength: map['cycle_length'] as int? ?? 28,
      estimatedOvulation: map['estimated_ovulation'] != null
          ? DateTime.parse(map['estimated_ovulation'] as String)
          : null,
      fertileWindowStart: map['fertile_window_start'] != null
          ? DateTime.parse(map['fertile_window_start'] as String)
          : null,
      fertileWindowEnd: map['fertile_window_end'] != null
          ? DateTime.parse(map['fertile_window_end'] as String)
          : null,
      isActivelyTtc: map['is_actively_ttc'] as bool? ?? true,
      createdAt: DateTime.parse(map['created_at'] as String),
      updatedAt: DateTime.parse(map['updated_at'] as String),
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'user_id': userId,
      'last_menstrual_period': lastMenstrualPeriod?.toIso8601String().substring(0, 10),
      'cycle_length': cycleLength,
      'estimated_ovulation': estimatedOvulation?.toIso8601String().substring(0, 10),
      'fertile_window_start': fertileWindowStart?.toIso8601String().substring(0, 10),
      'fertile_window_end': fertileWindowEnd?.toIso8601String().substring(0, 10),
      'is_actively_ttc': isActivelyTtc,
    };
  }

  // Calculate fertile window and ovulation
  static TtcTracker calculateFertileWindow({
    required String userId,
    required DateTime lmp,
    int cycleLength = 28,
  }) {
    final ovulationDay = lmp.add(Duration(days: cycleLength - 14));
    final fertileStart = ovulationDay.subtract(const Duration(days: 5));
    final fertileEnd = ovulationDay.add(const Duration(days: 1));

    return TtcTracker(
      id: '', // Will be generated by Supabase
      userId: userId,
      lastMenstrualPeriod: lmp,
      cycleLength: cycleLength,
      estimatedOvulation: ovulationDay,
      fertileWindowStart: fertileStart,
      fertileWindowEnd: fertileEnd,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    );
  }
}
